# Generated by Django 3.2.12 on 2022-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='vegetarian_option_selected',
            field=models.BooleanField(default=False),
        ),
    ]
